name: Convert POT to JSON
on:
  workflow_dispatch:
  push:
    branches: develop
    paths:
      - 'languages/cocoon-*.pot'

jobs:
  WP_POT_TO_JSON:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      id: setup_node_id
      with:
        node-version: 14
        cache: npm
    - name: install po2json
      run: npm install po2json --save
    - name: run po2json
      shell: bash
      run: |
        THEME_ROOT="/home/runner/work/cocoon/cocoon"
        LANGUAGES_PATH="$THEME_ROOT/languages"
        cd $LANGUAGES_PATH
        ls cocoon-*.pot | sed -r 's/cocoon-//g' | sed -r 's/.pot//g' | xargs -I LOCALE ${THEME_ROOT}/node_modules/po2json/bin/po2json -f jed1.x ${LANGUAGES_PATH}/cocoon-LOCALE.pot ${LANGUAGES_PATH}/cocoon-LOCALE-cocoon-blocks-js.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: languages/*.json
        token: ${{ secrets.GITHUB_TOKEN }}
        base: ${{ github.ref_name }}
        delete-branch: true
        title: "JSON Regenerated"
        commit-message: "JSON Regenerated"
        body: |
          JSON file regenerated by github actions
        branch: "pot-to-json-${{github.sha}}"