name: Generate POT file
on:
  workflow_dispatch:
  push:
    branches: develop
    paths-ignore:
      - 'languages/**'
      - '.github/**'
      - '.vscode/**'
      - 'crowdin.yml'
      - 'css/**'
      - 'scss/**'
      - 'images/**'
      - 'node_modules/**'
      - 'blocks/dist/**'
      - 'plugins/**'

jobs:
  WP_POT_Generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Wordpress POT Generation
      shell: bash
      run: |
        THEME_ROOT="/home/runner/work/cocoon/cocoon"
        SAVE_FULL_PATH="$THEME_ROOT/$SAVE_DIR/$DOMAIN.pot"

        # Download WP CLI
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/bin/wp

        # Regenerate POT file
        wp i18n make-pot "$THEME_ROOT" "$SAVE_FULL_PATH" --domain="$DOMAIN" --exclude="languages/*,plugins/*,blocks/dist/*,node_modules/*" --skip-audit --ignore-domain
      env:
        SAVE_DIR: 'languages'
        DOMAIN: 'cocoon'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: $SAVE_DIR/$DOMAIN.pot
        token: ${{ secrets.GITHUB_TOKEN }}
        base: ${{ github.ref_name }}
        delete-branch: true
        title: "POT Regenerated"
        commit-message: "POT Regenerated"
        body: |
          POT file regenerated by github actions
        branch: "pot-generator-${{github.sha}}"
      env:
        SAVE_DIR: 'languages'
        DOMAIN: 'cocoon'